apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: onebot
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/MohitJenkins/argocd-example-apps.git"
  destinations:
    - namespace: onebot-ns
      server: "https://kubernetes.default.svc"
  namespaceResourceWhitelist:
    - group: ""          
      kind: Service
    - group: ""         
      kind: ConfigMap
    - group: ""         
      kind: Secret
    - group: "apps"  
      kind: Deployment
  clusterResourceBlacklist:
    - group: "*"       
      kind: "*" 
  namespaceResourceBlacklist:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
